env:
  global:
    # GITHUB_TOKEN
    - secure: WhCCdF/3OfyoEyDn/5SfKrgNahlJ1YdV+65pCX0no3XRX4Z0n/gUJxSuhBPye96wqLoZTxjxytuiNTe2s4DdgbGWz5Yx2AsD7Xo0y7Ea2elvcnukD8JIzybc2mVhtN6YrVWXiRQl8OZR0uPK/3CE21vjOW4Y19/F+/FZOuLc6uQkyvfvKRuEDHFA7Uls3gjgoyxZq9vhW3F6RKDzgBvtkxN1Xzt7fF1ICIuwKYiseb+TL3rnzYi5MyuTJIIm9oBnzScHqNDb2gLekcQu3HfcUmaofqRGprAEhzFBETnrjjDgYzc57H0KIVefMqw2q2L8+ACuxpgZmhjscY0rdco8XkaSa4sTTKXRRq8+wQPtegyWBB8JfPWdtQqFz7kaYRZOSL1/vTaIBHPKszT0yUsbSKgoh7djrqC8zkmR9jkJDvr0kFp+A9+nO0Co365vi0urmkWJzJZGMf8E/eCXcl8xJhz9zTykx758IuKoBccIieRC2BMJ2xRwVrvqqk7dzwHfhnPO40gfSG+ugs5MOlqpTcbD7H07N41zzhQUHsy9rnGXA0fDpsklSuXfnhCPxuYEkTcTT5VaR/6qLGxBxDNExxP9xzj5RmsvtBlVb+4bJKhi0C17I02FK2bvllUxUcgp/Iyk3lSthkHLJLnyGKcrRkKPy95rQVjE5vHba8Iw4E8=

    # AWS_ACCESS_KEY_ID
    - secure: Fhwq2vcE4Ax2h0XEgqu5OQkKWRgQy1OWdtL+dTRqizIQhTSzs+hBQQM8gyQkEf3N3Vo4NF4CDCvN7sgwqF5Y/YA87hsVHCBNohsR0iSWUA/ptZxQEId3UKZ51lsP5ZcMeP66YfOobKWZyyMNA+WgxsZ3iTMkc/oL3TqQXIgy4uzJcheQ8/gQVxn8iPjNy7UQqP/VqPFgjMu58DDq4waIRek+0M2QkZ0ga0pX4wi2J4/II8oeEu7GikkFIC7x0sJmNxDtl91IxNcv7G9l7A1TnkVQycLJgQBK3hdfbAd0KeaIjlMboLusoRUcByJ2bNIdFOR+ZQVxwCejWO5CQV7e1iAVr03g3J6K6OVtUiMETqAmWGe5kSAWqe14ehiJBSf70UCHS853fIb7hZxBz2fYaykYJJK6M5Wh7EjrOSEjso0dqxcjGnUyhfh16T9IJVfVr9ZaVYIMnuV4FA4IlFgSuvU5v4FWpd9AL+cN/93PztDh/vg94tWhOqp1KIPo6C9FCxhF0/z7EdYIp+sB+epTcox/OiMFl9r7SrwQcpI07rf/iCwEtCm3jBf7Z0vRDU9ubrM3XRVqg2nN0S+ngmsPHaGgvlYLjuXvY1Jk4wHZ0MEFvOmnas2wzB/MfrrNvgwhF+O5RwvYu4yvOIsltGS+4jpGWTlFb+YEuJLmyk0r6Mw=

    # AWS_SECRET_ACCESS_KEY
    - secure: itpwyArphcq24tDCbWh3B6agOa7qPUoBNcJCGsvpnd9kyioLlZskkLHJxW2NPZgMXQT5A4Uqfm67fhw7IhRg60YljcYdDGEHlHmKrrNy+NFZoiIFsl9l/h9U/5tCv+97kDl7xIIynnktpa4w99twZGf43xOOH9+XbQk+EiPkTwRAjvyNtXS+1N2fDe96VgOUs3WIfPzb4AI3vWSYTrhlb9fs9rSxfBL9DTXvoxwNXpClVsQRR/RHJTgqkLP4OwoAv2QrSdgw/gSMw/nG4brG5fho7jMkHqHKsQf6z7AgnMxoOVOxF1klyWmGvKQRejFmT8bOEIJWswTOjByN/qgq+MpYi+aAqRNRpq+poUXn9xnLxtrlkjEO+UDbnYbzIAPJXtzmfjgtDMZ3sGWMkgUkCUV9ixbl9U1nVK9Y/L6Xg9zLHuumCfYQuoaBN+9bFFoRQ0YZRkrngXIDmiwUHMNpeYP2VHuDWzzd6Hm1sBB8CGHVGq01f3BpLUOhO/iy7Fw1URfStsgNbmmtMuJmQyn5LyoZtg/Byc9UUZoQLbsWF3TX1Yn8OL+tZTYNDyGzMkcvqa9x8TW47KLuR2WG7bLlmzLtzqLOQ9narPafr7KI7gjHxeqOGHJ0uirr7nVlmsruXFJ/BODIcxDrDX6UZGKeM4ohjhsBwK0LHjjIzwz0K5U=

    # GOOGLE_CAPTCHA_KEY
    - secure: dckD0tjL4fqkipubFm07ztZgvUSIOD79BuoTgBpECi2ZYcq5FUJ/uf+FRGacdhn33Xxh9rRelD2LM9VU5IB6/WmkajtXglPIiz2tixgbsbkhg9q/oZcWV6J8ljYOyK6ibXxlHsvVkrkOJNy0RIheEYrLVqTzQzWv4wa0nzkJNeIGgFuop1kjxIBw2E+HeBv9K0HFZJpGj5NeUB1k1lKWlMD4GlpSNv9bJ1m6DaI5iVGBFhlAFKR+gfpPemhwq0KgZZQ3qLou8lZr1sG4O2pDGtNLZgfczx4RTEODl1Ma+wYntVskoRA2HGcsuiNICGTCi5d1z1CBxcjaWtsbWeunng5YaZ7/E5a4a5+UeLFcNV38F7+HGSI7Y5KlpAXuMSAV/VwimR2puW5Rwn/edw39tSswG5KQf9/2rRqykMB5QDJkF9gI6/GmCyQsbcIPC5F90ANst11ciVTqXGaRlM52ET6WUUGxMVd9eYDP6vxQchQc2/1+6EIv4BC+Q0kaPljqJm3TstQ9GPS8F/FhBbTrw7UAN7GQyXrWs/JOyTT6oMXy4u8BIXEJdfWPqS7HdTguPhdhk6LwT1aH4vN6Qgpb2Qi2cXtZpKxuxCCRlUkbOUiGcmBbYNc6ID+45CBdWxDOr9QavcHHntjJUOZgvbIFeQ1+Cgb2xz45cXwnwYAnDlM=

    - AWS_REGION=us-east-1

jobs:
  include:
    - stage: "Deploy Asset Infrastructure"
      name: "sendEmail Bucket"
      language: node_js
      node_js: lts/*
      cache: npm
      before_install:
        - cd infrastructure
      install:
        - npm install -g aws-cdk@1.81.0
      script:
        - cdk synth -c GOOGLE_CAPTCHA_KEY="$GOOGLE_CAPTCHA_KEY" -c COMMIT_MESSAGE="$COMMIT_MESSAGE"
      deploy:
        provider: cloudformation
        access_key_id: "$AWS_ACCESS_KEY_ID"
        secret_access_key: "$AWS_SECRET_ACCESS_KEY"
        template: ./cdk.out/sendEmailBucket.template.json
        stack_name: sendEmailBucket
        region: "$AWS_REGION"
        capabilities: CAPABILITY_NAMED_IAM
        edge: true
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^deploy(-sendEmail)?$

    - stage: "Deploy Assets"
      name: "sendEmail Code"
      language: java
      jdk: oraclejdk11
      cache:
        directories:
          - $HOME/.m2
      before_install:
        - cd sendEmail
      install:
        - mvn clean install
      before_deploy:
        - cd target
      deploy:
        provider: s3
        access_key_id: "$AWS_ACCESS_KEY_ID"
        secret_access_key: "$AWS_SECRET_ACCESS_KEY"
        bucket: send-email-assets
        glob: sendEmail-jar-with-dependencies.jar
        upload_dir: assets
        storage_class: STANDARD_IA
        edge: true
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^deploy(-sendEmail)?$

    - stage: "Deploy Application"
      name: "Infrastructure"
      language: node_js
      node_js: lts/*
      cache: npm
      env:
        - COMMIT_MESSAGE="$(git log -1 --oneline --no-decorate)"
      before_install:
        - cd infrastructure
      install:
        - npm install -g aws-cdk@1.81.0
      script:
        - cdk synth -c GOOGLE_CAPTCHA_KEY="$GOOGLE_CAPTCHA_KEY" -c COMMIT_MESSAGE="$COMMIT_MESSAGE"
      deploy:
          provider: script
          script: cdk deploy --all --ci true --require-approval never -c GOOGLE_CAPTCHA_KEY="$GOOGLE_CAPTCHA_KEY" -c COMMIT_MESSAGE="$COMMIT_MESSAGE"
          edge: true
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^deploy(-(sendEmail|infrastructure))?$